version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lion_short
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
